version = 1

[[analyzers]]
name = "java"
enabled = true

[analyzers.meta]
target = "."
skip_files = [
    "src/test/**",          # Skip test files
    "build/**",             # Exclude Gradle build output
    "target/**"             # Exclude Maven artifacts (in case any)
]
max_file_size_bytes = 1000000
enabled_linters = [
    "checkstyle",           # Enforce Java code style
    "pmd",                  # Detect common issues
    "spring",               # Spring-specific best practices
    "security"              # Security vulnerabilities
]
